#!/usr/bin/env python3
#
# Create the gallery html page from the list of images found in img/
# using the database data.csv
#

from datetime import date
from pathlib import Path
from typing import Any, Dict, List, Optional, TextIO, Tuple
import argparse
import html
import os
import re

slug_re = re.compile(r"""
  ^
  \*\*\*\**     # 3 or more stars
  \s*           # whitespace
  ([a-z0-9-]+)  # slug (filename/URL); must contain only URL-safe characters
  \s*
  $
""", re.X)

field_re = re.compile(r"""
  ^
  ([a-z_]+)     # key
  \s*           # whitespace
  :
  \s*           # whitespace
  (.*)          # value
  \s*
  $
""", re.X)


def match_slug(line: str) -> Optional[str]:
    match = slug_re.match(line)
    if match:
        return match.group(1)
    else:
        return None


def split_notes(filename: str) -> List[Dict[str, Any]]:
    notes: List[Dict[str, Any]] = []
    note: Dict[str, Any] = {}
    def close_note() -> None:
        nonlocal note, notes
        if 'slug' in note:
            notes.append(note)
        note = { 'slug': '', 'lines': [], }
    with open(filename) as file:
        for line in file:
            slug = match_slug(line)
            if slug:
                close_note()
                note['slug'] = slug
            elif note:
                note['lines'].append(line)
            # else discard lines (at the beginning of the file)
    close_note()
    return notes


def parse_field(line: str) -> Optional[Tuple[str, str]]:
    match = field_re.match(line)
    if match:
        return (match.group(1), match.group(2))
    else:
        return None


# Format:
# - head section containing metadata section followed by document body.
# - metadata section is made of lines of the form "name: value",
#   blank lines are skipped until reaching a line that's not of the
#   "key: value".
# - the body is anything that follows the metadata section.
#
# Sample input:
#
#   title: Hello World
#   date: 2022-09-04
#   explainer: true
#   Something something
#   something
#
# If in the future we need more metadata or more structured metadata
# field values, we should switch to a standard data format like JSON or YAML
# for the head section.
#
def parse_note(note: Dict[str, Any]) -> Dict[str, Any]:
    slug: str = note['slug']
    stream = iter(note['lines'])
    title = None
    date_ = None
    explainer = False
    body = []
    # Parse head section
    try:
        while True:
            line = next(stream)
            field = parse_field(line)
            if field:
                key, value = field
                if key == '':
                    pass
                elif key == 'title':
                    title = value
                elif key == 'date':
                    try:
                        date_ = date.fromisoformat(value)
                    except ValueError:
                        raise Exception(f"{slug}: malformed date: {value}")
                elif key == 'explainer':
                    if value == 'true':
                        explainer = True
                    elif value == 'false':
                        explainer = False
                    else:
                        raise Exception(f"{explainer}: must be 'true' or 'false': {value}")
                else:
                    raise Exception(f"{slug}: unsupported field: {key}")
            else:
                body.append(line)
                break
    except StopIteration:
        pass
    if not title:
        raise Exception(f"{slug}: missing title")
    if not date_:
        raise Exception(f"{slug}: missing date")
    # Parse body
    try:
        while True:
            body.append(next(stream))
    except StopIteration:
        pass

    return {
        'slug': slug,
        'title': title,
        'date': date_,
        'body': body,
        'explainer': explainer,
    }


def parse_notes_from_file(filename: str) -> List[Dict[str, Any]]:
    raw_notes = split_notes(filename)
    notes = [ parse_note(x) for x in raw_notes ]
    # Sort from most recent to oldest
    key = lambda x: x['date']
    notes.sort(reverse=True, key=key)
    return notes

def get_note_url(note: Dict[str, Any]) -> str:
    return f"/notes/{note['slug']}/"

def get_note_explainer_url(note: Dict[str, Any]) -> str:
    return f"/notes/{note['slug']}/explainer/"

def get_optional_link_to_explainer(note: Dict[str, Any]) -> str:
    if note['explainer']:
        return f" \\[[explainer]({get_note_explainer_url(note)})\\]"
    else:
        return ""

def write_note_page(note: Dict[str, Any]) -> None:
    folder = Path(note['slug'])
    md_file = folder / 'index.md'
    os.makedirs(folder, exist_ok=True)
    explainer_link = get_optional_link_to_explainer(note)
    with open(md_file, 'w') as output:
        output.write(f"""\
% {note['title']}

{"".join(note['body'])}

_Martin Jambon, {note['date'].strftime("%B %d, %Y")}{explainer_link}_
""")


def write_explainer_template(note: Dict[str, Any]) -> None:
    """Create a folder and a template index.md to be filled by an AI.

    Do nothing if such a file already exists.
    """
    folder = Path(note['slug']) / 'explainer'
    md_file = folder / 'index.md'
    os.makedirs(folder, exist_ok=True)
    if not os.path.exists(md_file):
        with open(md_file, 'w') as output:
            output.write(f"""\
% Explainer: "{note['title']}"

*By ChatGPT*

This explainer is written to accompany and clarify Martin Jambon's short note:
**[{note['title']}]({get_note_url(note)})** (original note).

[missing contents]

---

*This explainer was written by ChatGPT to accompany Martin Jambon’s original note.*
""")

def write_note_inline(note: Dict[str, Any], md_output: TextIO) -> None:
    slug = note['slug']
    explainer_link = get_optional_link_to_explainer(note)
    md_output.write(f"""
### <a name="{slug}"></a>{note['title']}

{"".join(note['body'])}

_Martin Jambon, [{note['date'].strftime("%B %d, %Y")}]({slug}){explainer_link}_
""")


#
# Create a main page that serves as a table of contents
# and one page per entry found in the input file.
#
def generate(input_notes_file: str,
             md_output: TextIO,
             makefile_output: TextIO) -> None:
    md_output.write(
        f"""% Notes
<!-- generated by './build' -->
"""
    )
    makefile_output.write('NOTE_PATHS =')
    notes = parse_notes_from_file(input_notes_file)

    # write to index
    for note in notes:
        md_output.write(f"""* [{note['title']}](#{note['slug']})
""")
    for note in notes:
        write_note_inline(note, md_output)

    # write to makefile
    for note in notes:
        makefile_output.write(f""" \\\n  notes/{note['slug']}""")
        if note['explainer']:
            makefile_output.write(f""" \\\n  notes/{note['slug']}/explainer""")

    # write individual pages
    for note in notes:
        write_note_page(note)
        if note['explainer']:
            write_explainer_template(note)

    makefile_output.write("\n")

def main() -> None:
    with open('index.md', 'w') as md_output:
        with open('index.mk', 'w') as makefile_output:
            generate('notes.txt', md_output, makefile_output)

main()
